# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.2
yacl_version=3.9.3
modmenu_version=18.0.0-beta.1
sodium_version=0.8.12-beta.3

# Mod Properties
mod_version=1.0.4
maven_group=com.ntr
archives_base_name=NoTextureRotations

# Dependencies
fabric_version=0.148.2+26.1.2
