# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.2
yacl_version=3.9.6
modmenu_version=18.0.0
sodium_version=0.9.1

# Mod Properties
mod_version=1.0.5
mod_release_version=26.x
mod_mc_version_start=26.1
mod_mc_version_end=26.2
maven_group=com.ntr
archives_base_name=NoTextureRotations
java_version=25

# Dependencies
fabric_version=0.148.2+26.1.2
