name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v7

      - name: setup jdk
        uses: actions/setup-java@v5.6.0
        with:
          java-version: 21
          distribution: 'temurin'

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          dependency-graph: generate-and-submit

      - name: build
        run: ./gradlew build

      - name: capture build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: build/libs/
          if-no-files-found: error
          archive: false
