name: release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          dependency-graph: generate-and-submit

      - name: build
        run: ./gradlew build

      - name: Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/libs/*.jar"
          allowUpdates: false
          makeLatest: true
          body: |
            Supports MC 1.21.2
