name: release

on:
  workflow_dispatch:
    inputs:
      github:
        description: 'Github'
        required: true
        default: true
        type: boolean
      modrinth:
        description: 'Modrinth'
        required: true
        default: true
        type: boolean
      curseforge:
        description: 'CurseForge'
        required: true
        default: true
        type: boolean

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v7

      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          dependency-graph: generate-and-submit

      - name: build
        run: ./gradlew build

      - name: github release
        if: ${{ github.event.inputs.github }}
        run: ./gradlew publishGithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: modrinth release
        if: ${{ github.event.inputs.modrinth }}
        run: ./gradlew publishModrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

      - name: curseforge release
        if: ${{ github.event.inputs.curseforge }}
        run: ./gradlew publishCurseforge
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
